modLoader="javafml" 
loaderVersion="[32,)"
issueTrackerURL="https://github.com/Sunekaer/Structure-Expansion/issues"
[[mods]] 
modId="structureexpansion"
version="${file.jarVersion}" 
displayName="Structure Expansion"
displayURL="https://www.curseforge.com/minecraft/mc-mods/structure-expansion"
logoFile="logo.png"
authors="Sunekaer"
description='''
Structure Expansion
'''
[[dependencies.structureexpansion]] #optional
    modId="forge"
    mandatory=true
    versionRange="[32.0.0,)"
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.structureexpansion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
